((magit-commit nil)
 (magit-diff
  (("--" "init.el")
   "--no-ext-diff" "--stat")
  (("--" "init.el"))
  ("--no-ext-diff" "--stat")
  (("--" "init.el")
   "--ignore-space-change" "--ignore-all-space"))
 (magit-dispatch nil)
 (magit-ediff nil)
 (magit-fetch nil)
 (magit-gitignore nil)
 (magit-log
  (("--" "init.el"))
  ("-n20"
   ("--" "init.el")
   "--patch")
  (("--" "init.el")
   "--patch")
  ("-n256" "--graph" "--decorate")
  (("--" "init.el")
   "--graph" "--color")
  ("-n256" "--graph" "--color" "--decorate")
  ("-n256" "--graph" "--color" "--decorate" "--patch"))
 (magit-log:-n "20")
 (magit-merge nil)
 (magit-pull nil)
 (magit:-- "init.el" ""))
